language: ruby
rvm:
  - 2.4.4
  - 2.5.1

# Upgrading RubyGems
# see https://docs.travis-ci.com/user/languages/ruby/#Upgrading-RubyGems
before_install:
  - gem update --system
  - gem --version

script:
  - bundle exec rspec spec

# Configuring email notifications
# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
notifications:
  email: false

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
